#!/bin/bash
# XAUUSD Auto Report Generator
# Generate laporan markdown + chart ke analysis/
# Usage: bash scripts/report.sh

ENV_FILE="config/.env"
if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
fi

TS=$(date '+%Y-%m-%d %H:%M:%S')
DATE=$(date '+%Y-%m-%d')
FILE="analysis/report_${DATE}.md"

echo "📝 Generating report..."

# Generate chart
CHART_FILE=$(bash scripts/chart.sh 1h 3d "chart_${DATE}" 2>/dev/null | grep 'Chart saved' | sed 's/.*Chart saved: //')

# Run signal
SIGNAL_OUTPUT=$(bash scripts/signal.sh 2>/dev/null)

# Extract key values
PRICE=$(echo "$SIGNAL_OUTPUT" | grep 'Price:' | sed 's/.*Price: \$\([0-9.]*\).*/\1/')
SESSION=$(echo "$SIGNAL_OUTPUT" | grep -E '(LONDON-NY|LONDON|ASIAN|ROLLOVER)' | head -1 | sed 's/.*✅ //;s/.*⚠ //')
TREND=$(echo "$SIGNAL_OUTPUT" | grep 'Trend (5m)' | sed 's/.*Trend (5m)://;s/🔥//g;s/🟢//g;s/🔴//g;s/⚪//g;s/^[[:space:]]*//')
RSI=$(echo "$SIGNAL_OUTPUT" | grep 'RSI:' | head -1 | sed 's/.*RSI:[[:space:]]*\([0-9.]*\).*/\1/')
STOCH=$(echo "$SIGNAL_OUTPUT" | grep 'Stoch:' | head -1 | sed 's/.*K=[[:space:]]*\([0-9.]*\).*/\1/')
CCI=$(echo "$SIGNAL_OUTPUT" | grep 'CCI:' | head -1 | sed 's/.*CCI:[[:space:]]*\([-0-9.]*\).*/\1/')
ATR=$(echo "$SIGNAL_OUTPUT" | grep 'ATR:' | head -1 | sed 's/.*ATR:[[:space:]]*\([0-9.]*\).*/\1/')
BB_U=$(echo "$SIGNAL_OUTPUT" | grep 'BB Upper' | sed 's/.*\$\([0-9.]*\).*/\1/')
BB_L=$(echo "$SIGNAL_OUTPUT" | grep 'BB Lower' | sed 's/.*\$\([0-9.]*\).*/\1/')
ADX=$(echo "$SIGNAL_OUTPUT" | grep 'ADX:' | head -1 | sed 's/.*ADX:[[:space:]]*\([0-9.]*\).*/\1/')
ALIGNMENT=$(echo "$SIGNAL_OUTPUT" | grep 'TIMEFRAME' -A1 | tail -1 | sed 's/^[[:space:]]*//')
STRUCTURE=$(echo "$SIGNAL_OUTPUT" | grep 'STRUCTURE:' -A1 | tail -1 | sed 's/^[[:space:]]*//;s/— //')

STATE=$(bash scripts/monitor.sh 2>/dev/null | grep 'STATE:' | sed 's/.*STATE: //;s/^[^ ]* //')
BIAS=$(echo "$SIGNAL_OUTPUT" | grep 'mild bounce\|HIGH PROB\|mild reject' | head -1 | sed 's/^[[:space:]]*//')

# Build report
cat > "$FILE" << EOF
# 📊 XAUUSD Analysis Report — ${DATE}

**Generated:** ${TS}
**State:** ${STATE}
**Session:** ${SESSION}

---

## 📈 Chart

![XAUUSD Chart](${CHART_FILE})

---

## 📋 Market Overview

| Item | Value |
|------|-------|
| **Price** | \$${PRICE} |
| **Trend (5m)** | ${TREND} |
| **TF Alignment** | ${ALIGNMENT} |
| **Structure** | ${STRUCTURE} |
| **Signal Bias** | ${BIAS:-N/A} |
| **BB Upper** | \$${BB_U} |
| **BB Lower** | \$${BB_L} |

## ⚡ Momentum

| Indicator | Value | Status |
|-----------|-------|--------|
| **RSI** | ${RSI} | $([ -n "$RSI" ] && [ $(echo "$RSI < 35" | bc -l 2>/dev/null) -eq 1 ] && echo "Oversold" || [ $(echo "$RSI > 65" | bc -l 2>/dev/null) -eq 1 ] && echo "Overbought" || echo "Neutral") |
| **Stoch K** | ${STOCH} | $([ -n "$STOCH" ] && [ $(echo "$STOCH < 20" | bc -l 2>/dev/null) -eq 1 ] && echo "Oversold" || [ $(echo "$STOCH > 80" | bc -l 2>/dev/null) -eq 1 ] && echo "Overbought" || echo "Neutral") |
| **CCI** | ${CCI} | $([ -n "$CCI" ] && [ $(echo "$CCI < -100" | bc -l 2>/dev/null) -eq 1 ] && echo "Oversold" || [ $(echo "$CCI > 100" | bc -l 2>/dev/null) -eq 1 ] && echo "Overbought" || echo "Neutral") |
| **ADX** | ${ADX} | $([ -n "$ADX" ] && [ $(echo "$ADX > 25" | bc -l 2>/dev/null) -eq 1 ] && echo "Trending" || echo "Ranging") |
| **ATR** | ${ATR} | $([ -n "$ATR" ] && [ $(echo "$ATR > 8" | bc -l 2>/dev/null) -eq 1 ] && echo "⚠️ High" || echo "✅ Low") |

## 🔍 Analysis

${STRUCTURE}

${BIAS:+**Bias:** ${BIAS}}

${TREND:+**Trend:** ${TREND}}

${ALIGNMENT:+**Alignment:** ${ALIGNMENT}}

## 📝 Signal Detail

\`\`\`
${SIGNAL_OUTPUT}
\`\`\`

---
*Generated by XAUUSD Trading Project*
EOF

echo "  ✅ Report saved: ${FILE}"
echo "  📊 Chart: ${CHART_FILE}"

# Notify
bash scripts/notify.sh "📊 XAUUSD Report - \$${PRICE} | ${STATE}" "XAUUSD Report"
